---
- name: Create VPC
  ec2_vpc:
    state: "{{item.vpc_state}}"
    cidr_block: "{{item.vpc_cidr_block}}"
    region: "{{item.vpc_region}}"
    resource_tags: "{{item.vpc_resource_tags}}"
    subnets: "{{item.vpc_subnets}}"
  tags:
    - AWS
    - Network
    - VPC
  register: vpc_info
  with_items: vpc_list
